name: Project Deploy
 
on:
  push:
    branches:
     - main

env:
  AWS_IMAGE_BUCKET: s3-animal-is-friend
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Change Directory and Build with Gradle
      run: |
        cd AnimalIsFriend-BE
        chmod +x ./gradlew
        ./gradlew build
      shell: bash
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$AWS_IMAGE_BUCKET/$GITHUB_SHA.zip
