name: Project Deploy
on:
  push:
    branches:
     - main

env:
  AWS_IMAGE_BUCKET: s3-animal-is-friend
  CODEDEPLOY_NAME: animal-is-friend-github-actions
  CODEDEPLOY_GROUP: animal-is-friend-github-actions-group
  RESOUCE_PATH: ./AnimalIsFriend-BE/src/main/resources/application.yaml
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set yml file
      uses: microsoft/variable-substitution@v1
      with: 
        files: ${{ env.RESOUCE_PATH }}
      env:
        spring.datasource.url: ${{ secrets.DB_URL }}
        spring.datasource.username: ${{ secrets.DB_USERNAME }}
        spring.datasource.password: ${{ secrets.DB_PASSWORD }}
        spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
        spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
        jwt.secret-key: ${{ secrets.JWT_SECRET_KEY }}
        server.frontEnd: ${{ secrets.FRONT_END }}
        server.backEnd: ${{ secrets.BACK_END }}
        cloud.aws.s3.bucket: ${{ secrets.AWS_IMAGE_BUCKET }}
        cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_KEY_ID }}

    - name: Change Directory and Build with Gradle
      run: |
        cd AnimalIsFriend-BE
        chmod +x ./gradlew
        ./gradlew build
      shell: bash

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$AWS_IMAGE_BUCKET/$GITHUB_SHA.zip

    - name: Code Deploy
      run: |
        aws deploy create-deployment,
        --application-name $CODEDEPLOY_NAME,
        --deployment-config-name CodeDeployDefault.AllAtOnce,
        --deployment-group-name $CODEDEPLOY_GROUP,
        --s3-location bucket=$AWS_IMAGE_BUCKET,bundleType=zip,key=$GITHUB_SHA.zip,
